### ISSUE TITLE
[question]difference between cfltk and FLTK-C?

### ISSUE THREAD

**Issue by retsyo** [MoAlyousef/cfltk#204]
D.J.Peters supplied FLTK- C-1.3.3 for FreeBASIC, which is located on freebasic.net/forum/viewtopic.php?f=14&t=24547&hilit=fltk+c

Actually the lib can be used by other languages which support call functions in dynamic libraries on both windows and linux

so, what is the difference between cfltk and FLTK-C?

thanks

**Comment by MoAlyousef** [comment]
Hi
I downloaded the FLTK-C source code and it there doesn't appear to be much difference. 
FLTK-C appears to require FLTK 1.3.3 (the build fails against FLTK 1.4 headers), like calls to `->class_name()` which were long removed, and calls to `->driver()` as well.
cfltk requires FLTK 1.4 (it would fail against 1.3.3 headers). Calls to decorated_w(), decorated_h() and some dialog functions didn't exist prior to 1.4.
Both these issues can be worked around.
FLTK-C seems to be more complete as a binding since it provides more widget methods. Which can be eventually added to cfltk (or on a per need basis).
cfltk also assumes multi-threaded code, so most calls are wrapped in locks. 
cfltk also bundles stb_tt to handle custom font loading/usage, and also provides some window transparency setter and getter. Both features can be easily added to FLTK-C.
