### ISSUE TITLE
Request to add more precompiled / bundled configurations

### ISSUE THREAD

**Issue by caesay** [MoAlyousef/cfltk#236]
It would be great if win-x86 and win-arm64 were supported as fltk-bundled options as they are widely used.

Rationale:
- **win-x86**: I know win-x86 is basically a dead platform in that no new computers ship with it, but I still have users who are on x86 versions of win7 and win10 and I expect it will be many more years before we see it disappear completely. Since one of fltk's missions is to support old platforms it seems sensible to compile for it. Additionally, x86 binaries are smaller and can run very efficiently on both x64 and arm64 variations of windows (thanks to WoW64) making it a good compilation target if you are building a binary that needs to run everywhere. While x64 recently received virtualization support in win-arm64 in Windows 11, it's performance is not that great so it is still better to compile for x86 if you require running on both.
- **win-arm64**: This is becoming a more popular target recently in mobile windows computers due to performance and efficiency improvements. I expect that the market share of arm64 computers will continue to grow.

P.S. is there any reason this repo shouldn't move into the `fltk-rs` org? I went looking for it and struggled to find it before realising it was not a part of the org :)

**Comment by MoAlyousef** [comment]
Hi

It's complicated.
Currently the bundled targets are for x64 windows msvc and gnu since these are the most commonly used and tested. As of Rust 1.78, windows 10 is the minimum supported version.
The rust toolchain added *-win7-windows-* targets to be able to target windows 7. That means to provide full support for 32bit, 64bit and arm64 windows (7 and above), there would need be bundles for:
- x86_64-pc-windows-msvc
- x86_64-pc-windows-gnu
- i686-pc-windows-msvc
- i686-pc-windows-gnu
- x86_64-win7-windows-msvc (tier 3 target)
- i686-win7-windows-msvc (tier 3 target)
- aarch64-pc-windows-msvc (tier 2)
- aarch64-pc-windows-gnullvm (maybe, tier 2 without host tools)

All this while the windows-gnu target is moving towards ucrt, which might eventually require adding bundles targeting *-gnullvm for all windows architectures at some point, while keeping the *-gnu bundles since not most will migrate immediately.

While linux and macos only require 4 bundles combined.

That said, fltk-rs reads some environment variables which can tell it where to find bundles. The default is pointed here, but developers can point it to any url they prefer. These are CFLTK_BUNDLE_URL or CFLTK_BUNDLE_URL_PREFIX.

Regarding cfltk, it can be used standalone, its also use for the zig fltk bindings. So it might be better outside the fltk-rs org.

**Comment by caesay** [comment]
I'm not asking for win7 support. It seems to me the precompiled bundles are in C/C++ only, so the Rust toolchain being used is not important here. The `fltk-sys` project just needs to be able to find the right package (which is not necessarily a 1-1 mapping).

The `cfltk` project here seems to support these targets currently:
- lib_aarch64-unknown-linux-gnu.tar.gz
- lib_x86_64-unknown-linux-gnu.tar.gz
- lib_x86_64-apple-darwin.tar.gz
- lib_aarch64-apple-darwin.tar.gz
- lib_x86_64-pc-windows-gnu.tar.gz
- lib_x86_64-pc-windows-msvc.tar.gz

It's a bit more complicated because you are shipping gnu/msvc separately when probably msvc is enough? MSVC is the recommended toolchain by Rust itself and provides _much_ better results. GNU often has issues and it will take a lot of effort to support it properly going forward as you mentioned yourself.

The only targets I'm interested in (that are not already provided) are:
- lib_i686-pc-windows-msvc.tar.gz
- lib_aarch64-pc-windows-msvc.tar.gz

With just those two provided by this library, it would cover many of the Rust targets you mentioned
- x86_64-win7-windows-msvc (Rust >1.75)
- i686-win7-windows-msvc (Rust > 1.75)
- aarch64-pc-windows-msvc
- x86_64-pc-windows-msvc (and Win 7 on Rust <= 1.75)
- i686-pc-windows-msvc (and Win 7 on Rust <= 1.75)

I don't know the minimum rust version required to compile fltk/ fltk-sys but I think I remember reading somewhere that it was quite old, so anyone wanting to use win7 targets (either Rust 1.75 or one of the new tier 3's) can easily do so as long as is there a binary for cfltk which matches the cpu architecture.

**Comment by MoAlyousef** [comment]
I thnik adding those:
- lib_i686-pc-windows-msvc.tar.gz
- lib_aarch64-pc-windows-msvc.tar.gz
is reasonable.

**Comment by MoAlyousef** [comment]
I have added prebuilt bundles for windows 32bit and arm64 msvc.

**Comment by caesay** [comment]
Thanks a lot for that! Let me know if there's anywhere I can donate to the project. Really appreciate it.
